### ISSUE TITLE
인코딩 문제

### ISSUE THREAD

**Issue by ghost** [jungwuk-ryu/BatchFile-Project#1]
![스크린샷(1)](https://user-images.githubusercontent.com/67465462/99161746-a7b15280-2738-11eb-8aa5-fae679817a29.png)
학인 부탁드립니다.

**Comment by jungwuk-ryu** [comment]
해당 이슈는 0554fec 에서 해결되었습니다만 릴리즈 6.4를 다운로드받으신 것 같습니다.
인코딩 이슈가 해결된 버전을 릴리즈 하였으니 해당 버전으로 다시 확인해 주실 수 있으신가요? (https://github.com/jungwuk-ryu/BatchFile-Project/releases/tag/6.5)
