### ISSUE TITLE
파일 에러

### ISSUE THREAD

**Issue by ghost** [jungwuk-ryu/BatchFile-Project#2]
![스크린샷(2)](https://user-images.githubusercontent.com/67465462/99225767-eecc4000-282b-11eb-9b5c-f4c4931bd356.png)
확인 부탁드립니다.

>추가
실행은 되지만 작동하지 않습니다.

**Comment by jungwuk-ryu** [comment]
압축해제 프로그램에서 직접 실행할 경우 발생하는 문제로 보입니다.
3224449 에서 해결되었으니 [6.6 릴리즈](https://github.com/jungwuk-ryu/BatchFile-Project/releases/tag/6.6)에서 다시 시도해주세요.
